@startuml
'https://plantuml.com/class-diagram

+class List {
- tasks: Arraylist<ToDos>
+ addTask(ToDos task)
+ deleteTask(ToDos task)
+ getIncomplete(): ArrayList<ToDos>
+ getComplete(): ArrayList<ToDos>
+ getTasks(): ArrayList<ToDos>
+ clear()
+ saveList(File fileDirectory)
+ loadList(File fileDirectory): List

}

@enduml