@startuml
'https://plantuml.com/class-diagram

+class ToDos {
- desc: SimpleStringProperty
- dueDate: SimpleStringProperty
- isComplete: SimpleBooleanProperty
+ getDesc(): String
+ getdueDate(): String
+ getisComplete(): Boolean
+ editDesc(String str)
+ editdueDate(String date)
+ editisComplete()

}

@enduml